#!/usr/bin/env python

from optparse import OptionParser
from demod import demod_concatenate_fits

usage = """usage: %prog [options] folder1, folder2

Demodulate and concatenate all scientific dat files in a DAY folder
"""

parser = OptionParser(usage=usage)
(options, args) = parser.parse_args()

for folder in args:
    print('FOLDER %s' % folder)
    demod_concatenate_fits(folder)

